### ISSUE TITLE
javascript files are not loaded recursively

### ISSUE THREAD

**Issue by luckydonald** [MarshalX/telegram-crawler#2]
E.g. https://github.com/MarshalX/telegram-crawler/blob/3cd6a1bcefc0e074ef13e7e1ab425c19a0ef07b8/data/telegram.org/js/tgsticker.js#L118

- `tgsticker-worker.js`
  - `pako-inflate.min.js`
  - `rlottie-wasm.js`

**Comment by luckydonald** [comment]
I believe for now simply going for `["']/js/\w+.js["']` could work.

**Comment by luckydonald** [comment]
Manually including those files would work as well.

**Comment by MarshalX** [comment]
Huh. Sorry for long answer. I disabled notification for this repo :D

**Comment by MarshalX** [comment]
JavaScript files are adding without searching sub links in content for now. Its a good point to add the same analyzing like for text documents in it

**Comment by MarshalX** [comment]
https://github.com/MarshalX/telegram-crawler/commit/1cfa2b0f2440373e5f09122f473fa89281ffc616
